# GPIO: XIAO ESP32-C3 defaults
PIN_BC250_BUTTON = 2
PIN_BC250_SENSE = 3
PIN_CASE_BUTTON = 4
PIN_PS_ON = 5

# Power timing
DEBOUNCE_MS = 50
BC250_PRESS_MS = 250
FORCE_OFF_HOLD_MS = 4000
STARTUP_GRACE_MS = 10000

# BLE wake
WAKE_RSSI_MIN = -85
WAKE_HITS_REQUIRED = 2
WAKE_HIT_WINDOW_MS = 1500
WAKE_SCAN_MS = 3000
WEB_SCAN_MS = 5000

# Controller storage
CONTROLLERS_FILE = "controllers.json"
MAX_CONTROLLERS = 4

# Web scanning
MAX_WEB_PAYLOADS_PER_DEVICE = 4

# Wi-Fi
WIFI_CONNECT_TIMEOUT_MS = 15000
HOSTNAME = "bc250-controller"

# WEB UI
WEB_UI_DEBUG = False

# Initial controllers on a fresh installation
DEFAULT_CONTROLLERS = []
